version: '3.8'

services:
  testex:
    build: ./
    command: ./scripts/wait-for-postgres.sh db ./main
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432